// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessage.proto

package net.sz.game.message.proto;

public final class LoginMessage {
  private LoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code net.sz.game.message.proto.Protos_Register}
   *
   * <pre>
   * GL   game server 2  server
   * LG    server 2 game server
   * </pre>
   */
  public enum Protos_Register
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Login = 201101;</code>
     *
     * <pre>
     * GameServer 2 Server 注册请求
     * </pre>
     */
    Login(0, 201101),
    /**
     * <code>UserInfo = 201102;</code>
     *
     * <pre>
     *登录成功后用户信息
     * </pre>
     */
    UserInfo(1, 201102),
    ;

    /**
     * <code>Login = 201101;</code>
     *
     * <pre>
     * GameServer 2 Server 注册请求
     * </pre>
     */
    public static final int Login_VALUE = 201101;
    /**
     * <code>UserInfo = 201102;</code>
     *
     * <pre>
     *登录成功后用户信息
     * </pre>
     */
    public static final int UserInfo_VALUE = 201102;


    public final int getNumber() { return value; }

    public static Protos_Register valueOf(int value) {
      switch (value) {
        case 201101: return Login;
        case 201102: return UserInfo;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protos_Register>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Protos_Register>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protos_Register>() {
            public Protos_Register findValueByNumber(int number) {
              return Protos_Register.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.sz.game.message.proto.LoginMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protos_Register[] VALUES = values();

    public static Protos_Register valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Protos_Register(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:net.sz.game.message.proto.Protos_Register)
  }

  public interface CGLoginMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID();

    // optional int64 uid = 2;
    /**
     * <code>optional int64 uid = 2;</code>
     *
     * <pre>
     *登录服务器获取的用户id
     * </pre>
     */
    boolean hasUid();
    /**
     * <code>optional int64 uid = 2;</code>
     *
     * <pre>
     *登录服务器获取的用户id
     * </pre>
     */
    long getUid();

    // optional string uname = 3;
    /**
     * <code>optional string uname = 3;</code>
     *
     * <pre>
     *玩家登录用户名，第三方开放id
     * </pre>
     */
    boolean hasUname();
    /**
     * <code>optional string uname = 3;</code>
     *
     * <pre>
     *玩家登录用户名，第三方开放id
     * </pre>
     */
    java.lang.String getUname();
    /**
     * <code>optional string uname = 3;</code>
     *
     * <pre>
     *玩家登录用户名，第三方开放id
     * </pre>
     */
    com.google.protobuf.ByteString
        getUnameBytes();

    // optional string token = 4;
    /**
     * <code>optional string token = 4;</code>
     *
     * <pre>
     *登录服务器获取的token验证码
     * </pre>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 4;</code>
     *
     * <pre>
     *登录服务器获取的token验证码
     * </pre>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 4;</code>
     *
     * <pre>
     *登录服务器获取的token验证码
     * </pre>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    // optional int64 tokenTime = 5;
    /**
     * <code>optional int64 tokenTime = 5;</code>
     *
     * <pre>
     *登录服务器获取token生产时间，
     * </pre>
     */
    boolean hasTokenTime();
    /**
     * <code>optional int64 tokenTime = 5;</code>
     *
     * <pre>
     *登录服务器获取token生产时间，
     * </pre>
     */
    long getTokenTime();
  }
  /**
   * Protobuf type {@code net.sz.game.message.proto.CGLoginMessage}
   *
   * <pre>
   *客户端向网关服务器发起登录
   * </pre>
   */
  public static final class CGLoginMessage extends
      com.google.protobuf.GeneratedMessage
      implements CGLoginMessageOrBuilder {
    // Use CGLoginMessage.newBuilder() to construct.
    private CGLoginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CGLoginMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CGLoginMessage defaultInstance;
    public static CGLoginMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CGLoginMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CGLoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              net.sz.game.message.proto.LoginMessage.Protos_Register value = net.sz.game.message.proto.LoginMessage.Protos_Register.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uid_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              uname_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              token_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              tokenTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_CGLoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_CGLoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sz.game.message.proto.LoginMessage.CGLoginMessage.class, net.sz.game.message.proto.LoginMessage.CGLoginMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<CGLoginMessage> PARSER =
        new com.google.protobuf.AbstractParser<CGLoginMessage>() {
      public CGLoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CGLoginMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CGLoginMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];
    public static final int MSGID_FIELD_NUMBER = 1;
    private net.sz.game.message.proto.LoginMessage.Protos_Register msgID_;
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    public net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID() {
      return msgID_;
    }

    // optional int64 uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private long uid_;
    /**
     * <code>optional int64 uid = 2;</code>
     *
     * <pre>
     *登录服务器获取的用户id
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 uid = 2;</code>
     *
     * <pre>
     *登录服务器获取的用户id
     * </pre>
     */
    public long getUid() {
      return uid_;
    }

    // optional string uname = 3;
    public static final int UNAME_FIELD_NUMBER = 3;
    private java.lang.Object uname_;
    /**
     * <code>optional string uname = 3;</code>
     *
     * <pre>
     *玩家登录用户名，第三方开放id
     * </pre>
     */
    public boolean hasUname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string uname = 3;</code>
     *
     * <pre>
     *玩家登录用户名，第三方开放id
     * </pre>
     */
    public java.lang.String getUname() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uname = 3;</code>
     *
     * <pre>
     *玩家登录用户名，第三方开放id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUnameBytes() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string token = 4;
    public static final int TOKEN_FIELD_NUMBER = 4;
    private java.lang.Object token_;
    /**
     * <code>optional string token = 4;</code>
     *
     * <pre>
     *登录服务器获取的token验证码
     * </pre>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string token = 4;</code>
     *
     * <pre>
     *登录服务器获取的token验证码
     * </pre>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 4;</code>
     *
     * <pre>
     *登录服务器获取的token验证码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 tokenTime = 5;
    public static final int TOKENTIME_FIELD_NUMBER = 5;
    private long tokenTime_;
    /**
     * <code>optional int64 tokenTime = 5;</code>
     *
     * <pre>
     *登录服务器获取token生产时间，
     * </pre>
     */
    public boolean hasTokenTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 tokenTime = 5;</code>
     *
     * <pre>
     *登录服务器获取token生产时间，
     * </pre>
     */
    public long getTokenTime() {
      return tokenTime_;
    }

    private void initFields() {
      msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
      uid_ = 0L;
      uname_ = "";
      token_ = "";
      tokenTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTokenBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, tokenTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTokenBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, tokenTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.CGLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sz.game.message.proto.LoginMessage.CGLoginMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.sz.game.message.proto.CGLoginMessage}
     *
     * <pre>
     *客户端向网关服务器发起登录
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sz.game.message.proto.LoginMessage.CGLoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_CGLoginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_CGLoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sz.game.message.proto.LoginMessage.CGLoginMessage.class, net.sz.game.message.proto.LoginMessage.CGLoginMessage.Builder.class);
      }

      // Construct using net.sz.game.message.proto.LoginMessage.CGLoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        uname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        tokenTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_CGLoginMessage_descriptor;
      }

      public net.sz.game.message.proto.LoginMessage.CGLoginMessage getDefaultInstanceForType() {
        return net.sz.game.message.proto.LoginMessage.CGLoginMessage.getDefaultInstance();
      }

      public net.sz.game.message.proto.LoginMessage.CGLoginMessage build() {
        net.sz.game.message.proto.LoginMessage.CGLoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.sz.game.message.proto.LoginMessage.CGLoginMessage buildPartial() {
        net.sz.game.message.proto.LoginMessage.CGLoginMessage result = new net.sz.game.message.proto.LoginMessage.CGLoginMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uname_ = uname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.tokenTime_ = tokenTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sz.game.message.proto.LoginMessage.CGLoginMessage) {
          return mergeFrom((net.sz.game.message.proto.LoginMessage.CGLoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sz.game.message.proto.LoginMessage.CGLoginMessage other) {
        if (other == net.sz.game.message.proto.LoginMessage.CGLoginMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasUname()) {
          bitField0_ |= 0x00000004;
          uname_ = other.uname_;
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000008;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasTokenTime()) {
          setTokenTime(other.getTokenTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sz.game.message.proto.LoginMessage.CGLoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sz.game.message.proto.LoginMessage.CGLoginMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];
      private net.sz.game.message.proto.LoginMessage.Protos_Register msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public Builder setMsgID(net.sz.game.message.proto.LoginMessage.Protos_Register value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
        onChanged();
        return this;
      }

      // optional int64 uid = 2;
      private long uid_ ;
      /**
       * <code>optional int64 uid = 2;</code>
       *
       * <pre>
       *登录服务器获取的用户id
       * </pre>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 uid = 2;</code>
       *
       * <pre>
       *登录服务器获取的用户id
       * </pre>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>optional int64 uid = 2;</code>
       *
       * <pre>
       *登录服务器获取的用户id
       * </pre>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 uid = 2;</code>
       *
       * <pre>
       *登录服务器获取的用户id
       * </pre>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional string uname = 3;
      private java.lang.Object uname_ = "";
      /**
       * <code>optional string uname = 3;</code>
       *
       * <pre>
       *玩家登录用户名，第三方开放id
       * </pre>
       */
      public boolean hasUname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string uname = 3;</code>
       *
       * <pre>
       *玩家登录用户名，第三方开放id
       * </pre>
       */
      public java.lang.String getUname() {
        java.lang.Object ref = uname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uname = 3;</code>
       *
       * <pre>
       *玩家登录用户名，第三方开放id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUnameBytes() {
        java.lang.Object ref = uname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uname = 3;</code>
       *
       * <pre>
       *玩家登录用户名，第三方开放id
       * </pre>
       */
      public Builder setUname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uname = 3;</code>
       *
       * <pre>
       *玩家登录用户名，第三方开放id
       * </pre>
       */
      public Builder clearUname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uname_ = getDefaultInstance().getUname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uname = 3;</code>
       *
       * <pre>
       *玩家登录用户名，第三方开放id
       * </pre>
       */
      public Builder setUnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uname_ = value;
        onChanged();
        return this;
      }

      // optional string token = 4;
      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 4;</code>
       *
       * <pre>
       *登录服务器获取的token验证码
       * </pre>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string token = 4;</code>
       *
       * <pre>
       *登录服务器获取的token验证码
       * </pre>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 4;</code>
       *
       * <pre>
       *登录服务器获取的token验证码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 4;</code>
       *
       * <pre>
       *登录服务器获取的token验证码
       * </pre>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 4;</code>
       *
       * <pre>
       *登录服务器获取的token验证码
       * </pre>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000008);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 4;</code>
       *
       * <pre>
       *登录服务器获取的token验证码
       * </pre>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        token_ = value;
        onChanged();
        return this;
      }

      // optional int64 tokenTime = 5;
      private long tokenTime_ ;
      /**
       * <code>optional int64 tokenTime = 5;</code>
       *
       * <pre>
       *登录服务器获取token生产时间，
       * </pre>
       */
      public boolean hasTokenTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 tokenTime = 5;</code>
       *
       * <pre>
       *登录服务器获取token生产时间，
       * </pre>
       */
      public long getTokenTime() {
        return tokenTime_;
      }
      /**
       * <code>optional int64 tokenTime = 5;</code>
       *
       * <pre>
       *登录服务器获取token生产时间，
       * </pre>
       */
      public Builder setTokenTime(long value) {
        bitField0_ |= 0x00000010;
        tokenTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 tokenTime = 5;</code>
       *
       * <pre>
       *登录服务器获取token生产时间，
       * </pre>
       */
      public Builder clearTokenTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tokenTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.sz.game.message.proto.CGLoginMessage)
    }

    static {
      defaultInstance = new CGLoginMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.sz.game.message.proto.CGLoginMessage)
  }

  public interface GCLoginMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID();

    // optional int64 code = 2;
    /**
     * <code>optional int64 code = 2;</code>
     *
     * <pre>
     *登陆后的代码，0表示成功
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>optional int64 code = 2;</code>
     *
     * <pre>
     *登陆后的代码，0表示成功
     * </pre>
     */
    long getCode();

    // optional string msg = 3;
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     *非正常模式下的提示信息
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     *非正常模式下的提示信息
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     *非正常模式下的提示信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code net.sz.game.message.proto.GCLoginMessage}
   *
   * <pre>
   *网关服务器返回给客户端登录后信息
   * </pre>
   */
  public static final class GCLoginMessage extends
      com.google.protobuf.GeneratedMessage
      implements GCLoginMessageOrBuilder {
    // Use GCLoginMessage.newBuilder() to construct.
    private GCLoginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCLoginMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCLoginMessage defaultInstance;
    public static GCLoginMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GCLoginMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCLoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              net.sz.game.message.proto.LoginMessage.Protos_Register value = net.sz.game.message.proto.LoginMessage.Protos_Register.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCLoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCLoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sz.game.message.proto.LoginMessage.GCLoginMessage.class, net.sz.game.message.proto.LoginMessage.GCLoginMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GCLoginMessage> PARSER =
        new com.google.protobuf.AbstractParser<GCLoginMessage>() {
      public GCLoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCLoginMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCLoginMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];
    public static final int MSGID_FIELD_NUMBER = 1;
    private net.sz.game.message.proto.LoginMessage.Protos_Register msgID_;
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
     */
    public net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID() {
      return msgID_;
    }

    // optional int64 code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private long code_;
    /**
     * <code>optional int64 code = 2;</code>
     *
     * <pre>
     *登陆后的代码，0表示成功
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 code = 2;</code>
     *
     * <pre>
     *登陆后的代码，0表示成功
     * </pre>
     */
    public long getCode() {
      return code_;
    }

    // optional string msg = 3;
    public static final int MSG_FIELD_NUMBER = 3;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     *非正常模式下的提示信息
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     *非正常模式下的提示信息
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     *非正常模式下的提示信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
      code_ = 0L;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.GCLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sz.game.message.proto.LoginMessage.GCLoginMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.sz.game.message.proto.GCLoginMessage}
     *
     * <pre>
     *网关服务器返回给客户端登录后信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sz.game.message.proto.LoginMessage.GCLoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCLoginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCLoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sz.game.message.proto.LoginMessage.GCLoginMessage.class, net.sz.game.message.proto.LoginMessage.GCLoginMessage.Builder.class);
      }

      // Construct using net.sz.game.message.proto.LoginMessage.GCLoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCLoginMessage_descriptor;
      }

      public net.sz.game.message.proto.LoginMessage.GCLoginMessage getDefaultInstanceForType() {
        return net.sz.game.message.proto.LoginMessage.GCLoginMessage.getDefaultInstance();
      }

      public net.sz.game.message.proto.LoginMessage.GCLoginMessage build() {
        net.sz.game.message.proto.LoginMessage.GCLoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.sz.game.message.proto.LoginMessage.GCLoginMessage buildPartial() {
        net.sz.game.message.proto.LoginMessage.GCLoginMessage result = new net.sz.game.message.proto.LoginMessage.GCLoginMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sz.game.message.proto.LoginMessage.GCLoginMessage) {
          return mergeFrom((net.sz.game.message.proto.LoginMessage.GCLoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sz.game.message.proto.LoginMessage.GCLoginMessage other) {
        if (other == net.sz.game.message.proto.LoginMessage.GCLoginMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sz.game.message.proto.LoginMessage.GCLoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sz.game.message.proto.LoginMessage.GCLoginMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];
      private net.sz.game.message.proto.LoginMessage.Protos_Register msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public Builder setMsgID(net.sz.game.message.proto.LoginMessage.Protos_Register value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = Login];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.Login;
        onChanged();
        return this;
      }

      // optional int64 code = 2;
      private long code_ ;
      /**
       * <code>optional int64 code = 2;</code>
       *
       * <pre>
       *登陆后的代码，0表示成功
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 code = 2;</code>
       *
       * <pre>
       *登陆后的代码，0表示成功
       * </pre>
       */
      public long getCode() {
        return code_;
      }
      /**
       * <code>optional int64 code = 2;</code>
       *
       * <pre>
       *登陆后的代码，0表示成功
       * </pre>
       */
      public Builder setCode(long value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 code = 2;</code>
       *
       * <pre>
       *登陆后的代码，0表示成功
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0L;
        onChanged();
        return this;
      }

      // optional string msg = 3;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       *非正常模式下的提示信息
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       *非正常模式下的提示信息
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       *非正常模式下的提示信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       *非正常模式下的提示信息
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       *非正常模式下的提示信息
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       *非正常模式下的提示信息
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.sz.game.message.proto.GCLoginMessage)
    }

    static {
      defaultInstance = new GCLoginMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.sz.game.message.proto.GCLoginMessage)
  }

  public interface GCUserInfoMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
     */
    boolean hasMsgID();
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
     */
    net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID();
  }
  /**
   * Protobuf type {@code net.sz.game.message.proto.GCUserInfoMessage}
   *
   * <pre>
   *网关服务器返回给客户端登录后信息
   * </pre>
   */
  public static final class GCUserInfoMessage extends
      com.google.protobuf.GeneratedMessage
      implements GCUserInfoMessageOrBuilder {
    // Use GCUserInfoMessage.newBuilder() to construct.
    private GCUserInfoMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCUserInfoMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCUserInfoMessage defaultInstance;
    public static GCUserInfoMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GCUserInfoMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCUserInfoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              net.sz.game.message.proto.LoginMessage.Protos_Register value = net.sz.game.message.proto.LoginMessage.Protos_Register.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCUserInfoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCUserInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sz.game.message.proto.LoginMessage.GCUserInfoMessage.class, net.sz.game.message.proto.LoginMessage.GCUserInfoMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GCUserInfoMessage> PARSER =
        new com.google.protobuf.AbstractParser<GCUserInfoMessage>() {
      public GCUserInfoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCUserInfoMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCUserInfoMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];
    public static final int MSGID_FIELD_NUMBER = 1;
    private net.sz.game.message.proto.LoginMessage.Protos_Register msgID_;
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
     */
    public net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID() {
      return msgID_;
    }

    private void initFields() {
      msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.UserInfo;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sz.game.message.proto.LoginMessage.GCUserInfoMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.sz.game.message.proto.GCUserInfoMessage}
     *
     * <pre>
     *网关服务器返回给客户端登录后信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sz.game.message.proto.LoginMessage.GCUserInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCUserInfoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCUserInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sz.game.message.proto.LoginMessage.GCUserInfoMessage.class, net.sz.game.message.proto.LoginMessage.GCUserInfoMessage.Builder.class);
      }

      // Construct using net.sz.game.message.proto.LoginMessage.GCUserInfoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.UserInfo;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sz.game.message.proto.LoginMessage.internal_static_net_sz_game_message_proto_GCUserInfoMessage_descriptor;
      }

      public net.sz.game.message.proto.LoginMessage.GCUserInfoMessage getDefaultInstanceForType() {
        return net.sz.game.message.proto.LoginMessage.GCUserInfoMessage.getDefaultInstance();
      }

      public net.sz.game.message.proto.LoginMessage.GCUserInfoMessage build() {
        net.sz.game.message.proto.LoginMessage.GCUserInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.sz.game.message.proto.LoginMessage.GCUserInfoMessage buildPartial() {
        net.sz.game.message.proto.LoginMessage.GCUserInfoMessage result = new net.sz.game.message.proto.LoginMessage.GCUserInfoMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sz.game.message.proto.LoginMessage.GCUserInfoMessage) {
          return mergeFrom((net.sz.game.message.proto.LoginMessage.GCUserInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sz.game.message.proto.LoginMessage.GCUserInfoMessage other) {
        if (other == net.sz.game.message.proto.LoginMessage.GCUserInfoMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sz.game.message.proto.LoginMessage.GCUserInfoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sz.game.message.proto.LoginMessage.GCUserInfoMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];
      private net.sz.game.message.proto.LoginMessage.Protos_Register msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.UserInfo;
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
       */
      public net.sz.game.message.proto.LoginMessage.Protos_Register getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
       */
      public Builder setMsgID(net.sz.game.message.proto.LoginMessage.Protos_Register value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .net.sz.game.message.proto.Protos_Register msgID = 1 [default = UserInfo];</code>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = net.sz.game.message.proto.LoginMessage.Protos_Register.UserInfo;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.sz.game.message.proto.GCUserInfoMessage)
    }

    static {
      defaultInstance = new GCUserInfoMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.sz.game.message.proto.GCUserInfoMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sz_game_message_proto_CGLoginMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sz_game_message_proto_CGLoginMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sz_game_message_proto_GCLoginMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sz_game_message_proto_GCLoginMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_sz_game_message_proto_GCUserInfoMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_sz_game_message_proto_GCUserInfoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoginMessage.proto\022\031net.sz.game.messag" +
      "e.proto\"\220\001\n\016CGLoginMessage\022@\n\005msgID\030\001 \001(" +
      "\0162*.net.sz.game.message.proto.Protos_Reg" +
      "ister:\005Login\022\013\n\003uid\030\002 \001(\003\022\r\n\005uname\030\003 \001(\t" +
      "\022\r\n\005token\030\004 \001(\t\022\021\n\ttokenTime\030\005 \001(\003\"m\n\016GC" +
      "LoginMessage\022@\n\005msgID\030\001 \001(\0162*.net.sz.gam" +
      "e.message.proto.Protos_Register:\005Login\022\014" +
      "\n\004code\030\002 \001(\003\022\013\n\003msg\030\003 \001(\t\"X\n\021GCUserInfoM" +
      "essage\022C\n\005msgID\030\001 \001(\0162*.net.sz.game.mess" +
      "age.proto.Protos_Register:\010UserInfo*.\n\017P",
      "rotos_Register\022\013\n\005Login\020\215\243\014\022\016\n\010UserInfo\020" +
      "\216\243\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_sz_game_message_proto_CGLoginMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_sz_game_message_proto_CGLoginMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sz_game_message_proto_CGLoginMessage_descriptor,
              new java.lang.String[] { "MsgID", "Uid", "Uname", "Token", "TokenTime", });
          internal_static_net_sz_game_message_proto_GCLoginMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_sz_game_message_proto_GCLoginMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sz_game_message_proto_GCLoginMessage_descriptor,
              new java.lang.String[] { "MsgID", "Code", "Msg", });
          internal_static_net_sz_game_message_proto_GCUserInfoMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_net_sz_game_message_proto_GCUserInfoMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_sz_game_message_proto_GCUserInfoMessage_descriptor,
              new java.lang.String[] { "MsgID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
