// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMessage.proto

package net.sz.game.message.proto;

public final class GameMessage {
  private GameMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code net.sz.game.message.proto.Protos_Register}
   *
   * <pre>
   * GL   game server 2  server
   * LG    server 2 game server
   * </pre>
   */
  public enum Protos_Register
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RegisterHallServer = 801101;</code>
     *
     * <pre>
     * GameServer 2 Server 注册请求
     * </pre>
     */
    RegisterHallServer(0, 801101),
    ;

    /**
     * <code>RegisterHallServer = 801101;</code>
     *
     * <pre>
     * GameServer 2 Server 注册请求
     * </pre>
     */
    public static final int RegisterHallServer_VALUE = 801101;


    public final int getNumber() { return value; }

    public static Protos_Register valueOf(int value) {
      switch (value) {
        case 801101: return RegisterHallServer;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protos_Register>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Protos_Register>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protos_Register>() {
            public Protos_Register findValueByNumber(int number) {
              return Protos_Register.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.sz.game.message.proto.GameMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protos_Register[] VALUES = values();

    public static Protos_Register valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Protos_Register(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:net.sz.game.message.proto.Protos_Register)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021GameMessage.proto\022\031net.sz.game.message" +
      ".proto*+\n\017Protos_Register\022\030\n\022RegisterHal" +
      "lServer\020\315\3620"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
